name: Sahara
version: '${project.version}'
main: net.funoase.sahara.Sahara
api-version: '1.20'
author: RappyTV

commands:
  rylib:
    permission: sahara.reload

permissions:
  sahara.reload:
    default: op