name: RyLib
version: '${project.version}'
main: com.rappytv.rylib.RyLib
api-version: '1.20'
author: RappyTV

commands:
  rylib:
    permission: rylib.reload

permissions:
  rylib.reload:
    default: op